name: 'xmc-rust-audit-check'
description: 'Run cargo audit and check for security advisories'
author: 'xmc-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  token:
    description: GitHub Actions token
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
